name: Style Transfer
on:
  push:
    branches:
      - main

jobs:
  run-style-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
  run: |
    pip install -r requirements.txt
    pip install torch torchvision torchaudio

      - name: Run Style Transfer
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          python neural_style.py
